
# ==== CONFIGURE =====
# Use a Node 16 base image
FROM node:14
# Set the working directory to /app inside the container
WORKDIR /usr/app
# Copy app files
COPY package*.json ./
# ==== BUILD =====
# Install dependencies (npm ci makes sure the exact versions in the lockfile gets installed)
RUN npm install 
# Build the app
COPY . .
# ==== RUN =======
# Set the env to "production"
# Expose the port on which the app will be running (3000 is the default that `serve` uses)
EXPOSE 3000
# Start the app
CMD [ "npm", "start" ]