FROM node:14
WORKDIR /usr/app
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 3001
CMD ["npm", "run", "dev"]


#FROM node:current-alpine
#WORKDIR /server
#COPY package*.json
#RUN npm install
#COPY . .
#CMD ["node","server.js"]